services:
  mariadb:
    image: mariadb:10.6
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=secret_root_password
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=secret_password
    volumes:
      - bookstack_db_data_v2:/var/lib/mysql
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack_app
    environment:
      - APP_URL=http://localhost:6875
      - APP_KEY=base64:RZ5qld9TTcFqK1qy7ajUoTLiMEay6UuP687IXK+zjqQ=
      - DB_HOST=mariadb
      # --- Variables attendues par le script LinuxServer ---
      - DB_USER=bookstack
      - DB_PASS=secret_password
      - DB_DATABASE=bookstackapp
      - DB_USERNAME=bookstack
      - DB_PASSWORD=secret_password
      # --- Configuration LDAP ---
      - AUTH_METHOD=ldap
      - LDAP_SERVER=ldap://ldap.forumsys.com
      - LDAP_BASE_DN=dc=example,dc=com
      - LDAP_DN=cn=read-only-admin,dc=example,dc=com
      - LDAP_PASS=password
      - LDAP_USER_FILTER=(uid=$${user})
      - LDAP_ID_ATTRIBUTE=uid
      - LDAP_EMAIL_ATTRIBUTE=mail
      - LDAP_DISPLAY_NAME_ATTRIBUTE=cn
      - LDAP_VERSION=3
    volumes:
      - bookstack_app_data_v2:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - mariadb

volumes:
  bookstack_db_data_v2:
  bookstack_app_data_v2: